name: Composite Action Example

on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Run Composite Action
        id: run_composite_action
        uses: ./.github/actions/output-test-action
      - run: |
          echo ${{ steps.run_composite_action.outputs.sample_output }}

      