name: Stubbed Out Workflow

permissions:
  packages: read

on:
  workflow_dispatch:
    inputs:
      test-input:
        description: A Test Input
        required: true
        type: string

jobs:
  stub-job:
    runs-on: "ubuntu-latest"
    steps:
      - name: Hello World
        run: echo "Hello World!"
