name: Stubbed Out Workflow

permissions:
  packages: read

on:
  workflow_dispatch:
    inputs:
      input-alpha:
        description: "Some Input"
        type: string
  workflow_call:
    inputs:
      input-alpha:
        description: "Some Input"
        type: string
  push:
    paths-ignore:
      - '**.md'
    branches-ignore:
      - master


jobs:
  stub-job:
    runs-on: "ubuntu-latest"
    steps:
      - name: Hello World
        run: echo "Hello World!"
